#!/bin/sh -e
exec 2>&1
exec "/usr/bin/watchmedo" shell-command \
    --patterns="${WATCH_FILE_PATTERN}" \
    --recursive \
    --command='"/usr/bin/file-downloaded-hook" "${watch_src_path}"' \
    "/data/${GOOGLE_GROUP_NAME}"
